services:
  _defaults:
    autowire: true
    autoconfigure: true

  PhpGuild\RhapsodyAdminLteBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,RhapsodyAdminLteBundle.php}'
